[project]
name = "toon"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "python-toon>=0.1.3",
    "strands-agents>=1.16.0",
    "strands-agents-tools>=0.2.15",
]
